### ISSUE TITLE
The right way of building...

### ISSUE THREAD

**Issue by vsimko** [biggis-project/path-optimizer#12]
If I'm correct, there are currently the following pieces to be built:
- preprocessed datasets (using an R script)
- java code of the backend (using maven)
- docker image of the frontend (using docker-compose)
- docker image of the backend (using docker-compose)

Would it be possible to wrap this into a single step ?

Possible approaches:
- [x] Maven
- [ ] Shell script

**Comment by joachimrussig** [comment]
You are correct about the building steps. I would prefer Maven and it shouldn't be that much effort using the Maven AntRun plugin.

**Comment by vsimko** [comment]
I've assigned some issue (including this one) to a milestone.
